config/routes.rb
Rails.application.routes.draw do
  root to: 'home#game'

  get 'game', to: 'home#game'
  get 'exploreIssues', to: 'home#exploreIssues'
  get 'manageLikedQuotes', to: 'home#manageLikedQuotes'
  get 'sources', to: 'home#sources'
  get 'checkAnswer', to: 'home#checkAnswer'
  get 'issueInfo/(:issue_id)', to: 'home#issueInfoTemplate', as: :issue_info
  get 'likeQuote', to: 'home#likeQuote'
  get 'dislikeQuote', to: 'home#dislikeQuote'

  resources :users
  resources :sessions
  
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'signup', to: 'users#new', as: :signup
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

end

app/views/partials/_bottom_nav.html.erb
<div class="row">
	<div id="lowerRight">
			<i data-reveal-id="leaderboard" class="fa fa-trophy button round fa-4x small"></i>
		<%= link_to game_path do %>
	  		<% if @name && @name == "game" %>
	  			<i class="fa fa-gamepad button round small disabled"></i>
	  		<% else %>
	  			<i class="fa fa-gamepad button round small"></i>
	  		<% end %>
		<% end %>
		<%= link_to exploreIssues_path do %>
	  		<% if @name && @name == "exploration" %>
	  			<i class="fa fa-search button round small disabled"></i>
	  		<% else %>
	  			<i class="fa fa-search button round small"></i>
	  		<% end %>
		<% end %>
		<% if logged_in? %>
			<%= link_to manageLikedQuotes_path do %>
		  		<% if @name && @name == "management" %>
		  			<i class="fa fa-star button round small disabled"></i>
		  		<% else %>
		  			<i class="fa fa-star button round small"></i>
		  		<% end %>
			<% end %>
		<% end %>
	</div>
</div>

<div id="leaderboard" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">Top Smart Cookies</h2>
  <% if !$leaders.nil? %>
	  <table id="leaderBoard">
	  	<% $leaders.each do |l| %>
	  		<tr>
	  			<td width="400px"><h5><%= l.user_name %></h5></td>
	  			<td><h5><%= l.streak %></h5></td>
	  		</tr>
	  	<% end %>
	  </table>
  <% else %>
  	<h5 align="center">Seems like no one's playing our game yet...<i class="fa fa-frown-o"></i></h5>
  <% end %>
</div>

app/views/partials/_login.html.erb
<ul id="loginOptions">
  <li><%= link_to "Login", login_path %></li>
  <li><%= link_to "Signup", signup_path %></li>
  <!-- <li><a href="#">Connect with <i class="fa fa-facebook-official"></i></a></li> -->
</ul>

app/views/partials/_nav.html.erb
<!-- does partials/login need 4 columns? logo fonts needed. -->
<div id="informareLogo" class="small-4 columns" align="left">
  <%=link_to game_path do%>
    in&#8226;form&#8226;ar&#8226;e<%#= image_tag 'logo.png', alt: "informare", id: "informareLogo" %>
  <% end %>
</div>
<div id="title" class="small-4 columns">
  <% if @title %>
    <%= @title %>
  <% end %>
</div>
<div id="trackMyScore" class="small-4 columns" align="right">
  <% if !logged_in? %>
    <%= render partial: 'partials/login' %>
  <% else %>
    <%= link_to current_user.name, user_path(current_user) %> | <%= link_to "Logout", logout_path %>
  <% end %>
</div>